# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

{{- if .Values.auth_proxy.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: external-processing
  namespace: {{ include "gateway.namespace" . }}
spec:
  workloadSelector:
    labels:
      istio: gateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_proc
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
            value:
              failure_mode_allow: false
              message_timeout:
                seconds: 30
              processing_mode:
                request_header_mode: "SEND"
                response_header_mode: "SKIP"
                request_body_mode: "NONE"
                response_body_mode: "NONE"
                request_trailer_mode: "SKIP"
                response_trailer_mode: "SKIP"
              grpc_service:
                timeout:
                  seconds: 30
                envoy_grpc:
                  cluster_name: ext-proc-cluster
                  stat_prefix: "ingress_ext_proc"

---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-proc-cluster
  namespace: {{ include "gateway.namespace" . }}
spec:
  workloadSelector:
    labels:
      istio: gateway
  configPatches:
    - applyTo: CLUSTER
      match:
        context: GATEWAY
      patch:
        operation: ADD
        value: # Cluster specification
          name: ext-proc-cluster
          type: LOGICAL_DNS
          connect_timeout: 10s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: ext-proc-cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "auth-proxy.impt.svc.cluster.local"
                          protocol: TCP
                          port_value: 7001
          # [mTLS STRICT] below 'transportSocket' configuration is needed for the ingress
          # to communicate with the auth-proxy app over mTLS
          transportSocket:
            name: envoy.transport_sockets.tls
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              commonTlsContext:
                tlsCertificateSdsSecretConfigs:
                - name: default
                  sdsConfig:
                    apiConfigSource:
                      apiType: GRPC
                      grpcServices:
                      - envoyGrpc:
                          clusterName: sds-grpc
                      setNodeOnFirstMessageOnly: true
                      transportApiVersion: V3
                    resourceApiVersion: V3
              sni: "auth-proxy.impt.svc.cluster.local"
{{- end }}
