feature_flags_data: {}
main_namespace: impt
flyte_workflows:
  name: "jobs"
  domain: "production"

log_level: INFO

cert:
  name: signing-ie-certificate
  secretName: signing-ie-certificate
  algorithm: ECDSA
  size: 384
  duration: 4380h0m0s
  renewBefore: 24h0m0s
  ca_name: ca-issuer

global:
  telemetry_retention_geti: 30
  telemetry_retention_k8s: 10
  min_image_size: 32
  max_image_size: 20000
  min_video_size: 32
  max_video_width: 7680
  max_video_height: 4320
  max_video_length: 10800
  project_ie_key_source: "cert-manager"
  overwrite_resources_cpu_limits: "100"
  num_models_to_keep_in_storage: "-1"
  proxy_enabled: false
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

spicedb:
  fullname: impt-spice-db
  # To meet Intel crypto compliance,
  # use ECDSA P-521 for the CA and P-384 for the leafs.
  # use 5y for the CA and 1y for the leafs.
  tls:
    algorithm: ECDSA
    ca:
      name: ca-issuer
    leaf:
      size: 384
      duration: 4380h0m0s
      renewBefore: 24h0m0s

training:
  default_trainer_image_name: "impp/otx2-training"
  default_trainer_version: "2.2.0"
  mlflow_sidecar_image_name: "impp/mlflow-geti-store"

bucket_name_compileddatasetshards: compileddatasetshards
bucket_name_images: images
bucket_name_models: models
bucket_name_resultmedia: resultmedia
bucket_name_tensors: tensors
bucket_name_thumbnails: thumbnails
bucket_name_videos: videos
bucket_name_codedeployments: codedeployments
bucket_name_temporaryfiles: temporaryfiles
bucket_name_modelmesh: modelmesh
bucket_name_mlflowexperiments: mlflowexperiments
bucket_name_pretrainedweights: pretrainedweights

flyteNamespaceTemplate:
  # --- Enable or disable creating Flyte namespace in template. Enable when using helm as template-engine only. Disable when using `helm install ...`.
  enabled: true
