openldap:
  user_login: admin
  user_pass_sha: ""
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      memory: 300Mi

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsUser: 10001
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
    add:
      - CHOWN
      - FOWNER
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - KILL
      - NET_BIND_SERVICE

dex:
  rbac:
    create: true

  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10001
    capabilities:
      drop:
        - ALL 

  nodeSelector: {}

  resources:
    limits:
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 256Mi
