---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mongodb.fullname" . }}-compatibility-set
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - get