# Component Build Configuration
#
# This file optimizes CI/CD builds by configuring settings per component.
# Components not listed here use the 'defaults' section below.
components:
  interactive_ai/workflows/train/trainer/xpu:
    # Heavy builds requiring cleanup to fit into default GitHub runner disk space
    cleanup_type: all

  interactive_ai/workflows/train/trainer/gpu:
    # Heavy builds requiring cleanup to fit into default GitHub runner disk space
    cleanup_type: all

  interactive_ai/workflows/project_ie:
    integration_builder: false

  interactive_ai/workflows/dataset_ie:
    integration_builder: false

# Default configuration for unlisted components
defaults:
  cleanup_type: none
  integration_builder: true
