{{- if not .Values.global.istio_ambient_mesh }}
{{- $fullName := include "grafana.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
    {{- if .Values.global.istio_revision_name }}
    istio.io/rev: "{{ .Values.global.istio_revision_name }}"
    {{- end }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.global.istio_ingress_namespace }}/{{ .Values.global.istio_gateway_name }}
  http:
  - match:
    - uri:
        regex: {{ $ingressPath }}
    {{- if $.Values.global.cors_policy.enabled }}
    corsPolicy:
      allowHeaders: {{- include "geti-common.appendToArray" (dict "sourceArray" $.Values.global.cors_policy.allowed_headers) | indent 6 }}
      allowOrigins: {{- include "geti-common.formatKeyValuePair" (dict "sourceDict" $.Values.global.cors_policy.allowed_origins) | indent 6 }}
      allowMethods: {{- include "geti-common.appendToArray" (dict "sourceArray" $.Values.global.cors_policy.allowed_methods) | indent 6 }}
      maxAge: {{ .Values.global.cors_policy.max_age | quote }}
      allowCredentials: {{ .Values.global.cors_policy.allow_credentials }}
    {{- end }}
    headers:
      response:
        set:
{{ .Values.ingress.istioIngressResponseHeaders | indent 10 }}
        remove:
{{ .Values.global.stripped_headers | indent 8 }}
    timeout: 360s
    route:
    - destination:
        host: {{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ $servicePort }}
      headers:
        request:
          remove:
          - Authorization
{{- end }}
