task: classification

hyperparameters:
  dataset_preparation:
    augmentation:
      random_resize_crop:
        enable: true
        crop_ratio_range:
          - 0.08
          - 1.0
        aspect_ratio_range:
          - 0.75
          - 1.34
      random_affine:
        enable: false
        max_rotate_degree: 10.0
        max_translate_ratio: 0.1
        scaling_ratio_range:
          - 0.5
          - 1.5
        max_shear_degree: 2.0
      random_horizontal_flip:
        enable: true
        probability: 0.5
      random_vertical_flip:
        enable: false
        probability: 0.5
      gaussian_blur:
        enable: false
        kernel_size: 5
        sigma:
          - 0.1
          - 2.0
        probability: 0.5
      color_jitter:
        enable: false
        brightness:
          - 0.875
          - 1.125
        contrast:
          - 0.5
          - 1.5
        saturation:
          - 0.5
          - 1.5
        hue:
          - -0.05
          - 0.05
        probability: 0.5
      gaussian_noise:
        enable: false
        mean: 0.0
        sigma: 0.1
        probability: 0.5
  evaluation:
    metric: accuracy
  training:
    max_epochs: 100
    early_stopping:
      enable: true
      patience: 7
    allowed_values_input_size:
      - 64
      - 128
      - 224
      - 256
      - 320
      - 384
      - 480
      - 560
    input_size_width: 224
    input_size_height: 224
