id: Custom_Image_Classification_EfficientNet-B3
name: EfficientNet-B3

description: "EfficientNet-B3 is a scaled-up version of EfficientNet-B0, offering improved accuracy by increasing the network's depth, width, and resolution using compound scaling. It provides a good balance between performance and computational cost, making it suitable for applications that require higher accuracy without significantly sacrificing efficiency."
stats:
  gigaflops: 1.92
  trainable_parameters: 12.0
  performance_ratings:  # scores range from 1 (below average) to 3 (excellent)
    accuracy: 3
    training_time: 2
    inference_speed: 2

hyperparameters:
  training:
    learning_rate: 0.0049
