id: Custom_Image_Classification_MobileNet-V3-small
name: MobileNet-V3-small

description: "MobileNetV3-Small is an ultra-efficient classification model designed specifically for low-latency, resource-constrained environments. With a compact architecture and efficient components such as SE modules and hard-swish activation, it achieves good accuracy with minimal computational overhead, ideal for IoT and mobile applications."
stats:
  gigaflops: 0.11
  trainable_parameters: 1.77
  performance_ratings:  # scores range from 1 (below average) to 3 (excellent)
    accuracy: 1
    training_time: 3
    inference_speed: 3
support_status: deprecated

hyperparameters:
  training:
    learning_rate: 0.0058
