id: Custom_Image_Classification_MobileNet-V3-large-1x
name: MobileNet-V3-large-1x

description: "MobileNetV3-Large is a lightweight and efficient image classification model tailored for high-performance applications on mobile and embedded devices. It combines MobileNetV2’s inverted residuals with enhancements like squeeze-and-excitation (SE) blocks, hard-swish activation, and neural architecture search for optimal speed-accuracy trade-offs."
stats:
  gigaflops: 0.44
  trainable_parameters: 5.4
  performance_ratings:  # scores range from 1 (below average) to 3 (excellent)
    accuracy: 2
    training_time: 3
    inference_speed: 3

hyperparameters:
  training:
    learning_rate: 0.0058
