minAllocableCpu: 0.5
domain: ""
platformVersion:
buildVersion:
intelEmail:
# Owned namespaces are populated via impt-values template.
invite_user_expiration: 1440
acc_svc_invite_user_expiration: 43200
not_activated_user_expiration_in_days: 30
max_number_of_users_per_org: ""
password_reset_expiration: 15
log_level: INFO
desired_disk_free: "30GB"
render_gid: 0
accelerator:
  type: 'cpu'
  name: ''

global:
  serverAddress: ''
  grafana_enabled: ''
  s3_credentials_provider: local
  mongodb_credentials_provider: local
  mongodb_address: ""
  mongodb_database_name: geti
  max_number_of_trainable_tasks: 2
  max_number_of_labels: 1000
  min_image_size: 32
  max_image_size: 20000
  min_video_size: 32
  max_video_width: 7680
  max_video_height: 4320
  max_video_length: 10800
  kafka_topic_prefix: ""
  num_models_to_keep_in_storage: "-1"

feature_flags_data: {}

bucket_name_compileddatasetshards: compileddatasetshards
bucket_name_images: images
bucket_name_models: models
bucket_name_tensors: tensors
bucket_name_thumbnails: thumbnails
bucket_name_videos: videos
bucket_name_codedeployments: codedeployments
bucket_name_temporaryfiles: temporaryfiles
bucket_name_modelmesh: modelmesh
bucket_name_mlflowexperiments: mlflowexperiments
bucket_name_pretrainedweights: pretrainedweights
