id: Object_Detection_Deim_DFine_X
name: Deim-DFine-X

description: "DEIM is an advanced training framework designed to enhance the matching mechanism in DETRs, enabling faster convergence and improved accuracy."
stats:
  gigaflops: 202
  trainable_parameters: 62
  performance_ratings:  # scores range from 1 (below average) to 3 (excellent)
    accuracy: 3
    training_time: 1
    inference_speed: 1

hyperparameters:
  training:
    learning_rate: 0.0005
    allowed_values_input_size:
      - 640
    input_size_width: 640
    input_size_height: 640
  dataset_preparation:
    augmentation:
      iou_random_crop: null
      random_affine: null
      random_horizontal_flip: null
      random_vertical_flip: null
      gaussian_blur: null
      color_jitter: null
      gaussian_noise: null
