id: Object_Detection_Deim_DFine_M
name: Deim-DFine-M

description: "DEIM is an advanced training framework designed to enhance the matching mechanism in DETRs, enabling faster convergence and improved accuracy."
stats:
  gigaflops: 57
  trainable_parameters: 19
  performance_ratings:  # scores range from 1 (below average) to 3 (excellent)
    accuracy: 2
    training_time: 2
    inference_speed: 2

hyperparameters:
  training:
    learning_rate: 0.0004
    allowed_values_input_size:
      - 640
    input_size_width: 640
    input_size_height: 640
