id: Object_Detection_RTMDet_tiny
name: RTMdet-Tiny

description: "RTMDet is a real-time object detection algorithm that builds on a unified and scalable architecture optimized for both speed and accuracy. It features an efficient backbone, a strong neck with task-specific design, and a decoupled head for improved classification and localization. "
stats:
  gigaflops: 32
  trainable_parameters: 4.8
  performance_ratings:  # scores range from 1 (below average) to 3 (excellent)
    accuracy: 3
    training_time: 1
    inference_speed: 1

hyperparameters:
  training:
    learning_rate: 0.0007
    input_size_width: 640
    input_size_height: 640
