id: Custom_Object_Detection_Gen3_SSD
name: SSD-MobilenetV2

description: "SSD (Single Shot MultiBox Detector) is a real-time, anchor-based object detection algorithm that performs object localization and classification in a single forward pass. It uses a convolutional backbone and multiple feature maps at different scales to detect objects of various sizes. SSD balances speed and accuracy, making it efficient for deployment on resource-constrained devices."
stats:
  gigaflops: 9.4
  trainable_parameters: 7.6
  performance_ratings:  # scores range from 1 (below average) to 3 (excellent)
    accuracy: 1
    training_time: 2
    inference_speed: 3

hyperparameters:
  training:
    learning_rate: 0.01
    allowed_values_input_size:
      - 128
      - 256
      - 384
      - 512
      - 640
      - 864
      - 992
      - 1024
    input_size_width: 864
    input_size_height: 864
