apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-storage-volume-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageLimit }}
  {{- if eq .Values.storageClassName "local-storage" }}
  volumeName: "data-storage-volume"
  {{- end }}