{{- if .Values.global.install_telemetry_stack }}
{{- if and (eq .Values.mode "deployment") (.Values.configMap.create) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  relay: |
    {{- include "opentelemetry-collector.deploymentConfig" . | nindent 4 -}}
{{- end }}
{{- end }}