name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature] <short description>"
labels: [feature-request]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: 📄 Description
      description: Provide a brief overview of the proposed feature.
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: 🎯 Objective
      description: What is the main goal of this feature?
    validations:
      required: true
