name: 'Read Component Configuration'
description: 'Read component configuration from YAML file'

inputs:
  component_dir:
    description: 'Component directory from the repo root'
    required: true
  config_file:
    description: 'Path to configuration YAML file'
    required: false
    default: '.github/components-config.yaml'

outputs:
  cleanup_type:
    description: 'Type of cleanup to perform'
    value: ${{ steps.config.outputs.cleanup_type }}
  integration_builder:
    description: 'If integration tests should be executed in a builder container'
    value: ${{ steps.config.outputs.integration_builder }}

runs:
  using: 'composite'
  steps:
    - name: Read component configuration
      id: config
      shell: bash
      env:
        COMPONENT_DIR: ${{ inputs.component_dir }}
        CONFIG_FILE: ${{ inputs.config_file }}
      run: |
        
        get_config_value() {
          COMPONENT="$COMPONENT_DIR" KEY="$1" yq eval -r '
          .defaults as $defaults |
          (.components[env(COMPONENT)] // {}) as $component |
          ($defaults * $component)[env(KEY)]
          ' "$CONFIG_FILE"
        }

        cleanup_type=$(get_config_value "cleanup_type")
        integration_builder=$(get_config_value "integration_builder")
        
        echo "cleanup_type=$cleanup_type" >> $GITHUB_OUTPUT
        echo "integration_builder=$integration_builder" >> $GITHUB_OUTPUT
        
        echo "=== Component Configuration ==="
        echo "Component: $COMPONENT_DIR"
        echo "cleanup_type: $cleanup_type"
        echo "integration_builder: $integration_builder"
        echo "==============================="
