id: Custom_Counting_Instance_Segmentation_MaskRCNN_SwinT_FP16
name: MaskRCNN-Swin-T

description: "This model combines the Mask R-CNN framework with a Swin-Tiny transformer backbone, leveraging hierarchical attention and shifted windows for better spatial understanding. It delivers enhanced instance segmentation performance, especially on complex scenes, while maintaining a lightweight transformer design."
stats:
  gigaflops: 264.0
  trainable_parameters: 47.4
  performance_ratings:  # scores range from 1 (below average) to 3 (excellent)
    accuracy: 3
    training_time: 1
    inference_speed: 1

hyperparameters:
  training:
    learning_rate: 0.0001
    input_size_width: 1344
    input_size_height: 1344
