id: Custom_Counting_Instance_Segmentation_MaskRCNN_ResNet50
name: MaskRCNN-ResNet50-V1

description: "Mask R-CNN with a ResNet-50 backbone is a widely used instance segmentation model that balances accuracy and speed. The ResNet-50 backbone provides strong feature extraction, while the Mask R-CNN head enables precise object detection and mask prediction for each instance. Note: this version is deprecated, please use v2 if possible."
stats:
  gigaflops: 200.0
  trainable_parameters: 47.8
  performance_ratings:  # scores range from 1 (below average) to 3 (excellent)
    accuracy: 2
    training_time: 2
    inference_speed: 2
support_status: deprecated

supported_gpus:
  intel: false

hyperparameters:
  training:
    learning_rate: 0.007
