mongo:
  services:
    - dataset-ie
    - resource
    - director
    - gateway
    - project-ie
    - visual-prompt
    - spice-db
    - inference-job
    - jobs-ms
    - jobs-scheduler
    - jobs-scheduling-policy
    - jobs
    - auto-train-controller
    - inference-gateway
  secret_data: |
    {{- $backward_mongodb_username := randAlpha 6 | b64enc | quote }}
    {{- $backward_mongodb_password := randAlphaNum 12 | b64enc | quote }}
    {{- $mongodb_username := randAlpha 6 | b64enc | quote }}
    {{- $mongodb_password := randAlphaNum 12 | b64enc | quote }}
    {{- $previous := lookup "v1" "Secret" .Release.Namespace (include "mongodb.secretName" .) }}
        {{- if $previous }}
    # `index` function is necessary because the property name contains a dash.
    # Otherwise $previous.data.mongodb_password would have worked too.
    mongodb-password: {{ index $previous.data "mongodb-password" }}
    mongodb-username: {{ index $previous.data "mongodb-username" }}
    {{ else }}
    mongodb-username: {{ $backward_mongodb_username }}
    mongodb-password: {{ $backward_mongodb_password }}
    {{- end }}
    {{- range .Values.mongo.services }}
    {{- if $previous }}
    {{- if (index $previous.data (printf "%s-%s" . "mongodb-password")) }}
    {{ . }}-mongodb-password: {{ index $previous.data (printf "%s-%s" . "mongodb-password") }}
    {{ . }}-mongodb-username: {{ index $previous.data (printf "%s-%s" . "mongodb-username") }}
    {{ else }}
    {{ . }}-mongodb-username: {{ randAlpha 6 | b64enc | quote }}
    {{ . }}-mongodb-password: {{ randAlphaNum 12 | b64enc | quote }}
    {{- end }}
    {{ else }}
    {{ . }}-mongodb-username: {{ randAlpha 6 | b64enc | quote }}
    {{ . }}-mongodb-password: {{ randAlphaNum 12 | b64enc | quote }}
    {{- end }}
    {{- end }}

postgresql:
  auth:
    init_database: spicedb
  accountservice_postgresql_db: accountservice
  creditsystem_postgresql_db: creditsystem
  flyte_db_enabled: true
  flyte_db_config:
    port: 5432
    host: impt-postgresql.impt
    dbname: flyte
    options: "sslmode=disable"

spicedb:
  clusterDomain: cluster.local

global:
  credit_system_enabled: false

kafka:
  secretName: kafka-jaas
  clientUsers:
    - admin
    - dataset-ie
    - director
    - jobs-scheduler
    - resource
    - flyte
    - account-service
    - notifier
    - project-ie
    - visual-prompt
    - gateway
    - user-directory
  creditSystemUser: credit-system

namespace:
  istio: istio-system

smtp:
  smtp_enabled: false
  from_mail: "no-reply@geti.intel.com"
  from_name: "Intel Geti"
  smtp_port: ""
  smtp_host: ""
  smtp_login: ""
  smtp_password: ""
  
main_namespace: impt
flyte_workflows:
  name: "jobs"
  domain: "production"
