{{- if .Values.smtp.smtp_enabled }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace (printf "%s-email-config" .Release.Namespace) }}
{{- if $previous }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-email-config
  namespace: {{ .Release.Namespace }}
data:
  from_mail: {{ index $previous.data "from_mail" }}
  from_name: {{ index $previous.data "from_name" }}
  smtp_port: {{ index $previous.data "smtp_port" }}
  smtp_host: {{ index $previous.data "smtp_host" }}
  smtp_login: {{ index $previous.data "smtp_login" | default "" | quote }}
  smtp_password: {{ index $previous.data "smtp_password" | default "" | quote }}
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-email-config
  namespace: {{ .Release.Namespace }}
data:
  from_mail: {{ .Values.smtp.from_mail | b64enc | quote }}
  from_name: {{ .Values.smtp.from_name | b64enc | quote }}
  smtp_port: {{ .Values.smtp.smtp_port | b64enc | quote }}
  smtp_host: {{ .Values.smtp.smtp_host | b64enc | quote }}
  smtp_login: {{ .Values.smtp.smtp_login | b64enc | quote }}
  smtp_password: {{ .Values.smtp.smtp_password | b64enc | quote }}
{{- end }}
{{- end }}
