---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etcd.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "etcd.fullname" . }}-auth
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "etcd.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "etcd.fullname" . }}-auth
subjects:
  - kind: ServiceAccount
    name: {{ include "etcd.fullname" . }}-auth
    namespace: {{ .Release.Namespace }}
