---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $previous := lookup "v1" "Secret" .Release.Namespace (include "etcd.fullname" .) -}}
  {{- if $previous }}
  # `index` function is necessary because the property name contains a dash.
  etcd-root-password: {{ index $previous.data "etcd-root-password" }}
  {{ else }}
  etcd-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
