id: Custom_Rotated_Detection_via_Instance_Segmentation_MaskRCNN_EfficientNetB2B
name: MaskRCNN-EfficientNetB2B

description: "This model integrates Mask R-CNN with an EfficientNet-B2B backbone, combining the accuracy of a region-based detection approach with the efficiency of the EfficientNet architecture. It offers strong instance segmentation performance with reduced computational cost, making it suitable for scenarios where both precision and efficiency are important."
stats:
  gigaflops: 68.48
  trainable_parameters: 12.9
  performance_ratings:  # scores range from 1 (below average) to 3 (excellent)
    accuracy: 2
    training_time: 3
    inference_speed: 3

hyperparameters:
  training:
    learning_rate: 0.007
