type: object
properties:
  task_configs:
    type: array
    description: Array containing configuration for each task in the project
    items:
      $ref: "project_configuration_task_config.yaml"

required:
  - task_configs

example:
  task_configs:
    - task_id: "61012cdb1d38a5e71ef3bafd"
      training:
        constraints:
        - key: "min_images_per_label"
          name: "Minimum images per label"
          description: "Minimum number of images that must be present for each label to train"
          type: int
          default_value: 0
          min_value: 0
          max_value: null
          value: 0
      auto_training:
        - key: "enable"
          name: "Enable auto training"
          description: "Whether automatic training is enabled for this task"
          type: bool
          default_value: true
          value: true
        - key: "enable_dynamic_required_annotations"
          name: "Enable dynamic required annotations"
          description: "Whether to dynamically adjust the number of required annotations"
          type: bool
          default_value: false
          value: false
        - key: "min_images_per_label"
          name: "Minimum images per label"
          description: "Minimum number of images needed for each label to trigger auto-training"
          type: int
          default_value: 12
          min_value: 3
          max_value: null
          value: 1
