# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

# Unfortunately, Istio (Envoy) supports only P-256 ECDSA certificates,
# see https://github.com/envoyproxy/envoy/issues/10855

{{- $previous := lookup "v1" "Secret" .Release.Namespace "custom-tls" -}}
{{- if not $previous }}
  {{- if and .Values.tls.key_file .Values.tls.cert_file }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: custom-tls
  namespace: {{ include "gateway.namespace" . }}
data:
  tls.key: {{ .Values.tls.key_file | quote }}
  tls.crt: {{ .Values.tls.cert_file | quote }}
  {{- else }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: custom-tls
  namespace: {{ include "gateway.namespace" . }}
spec:
  secretName: custom-tls
  duration: 4380h0m0s
  renewBefore: 24h0m0s
  dnsNames:
    - Intel Geti
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: ClusterIssuer
    group: cert-manager.io
  {{- end }}
{{- else }}
# do nothing
{{- end }}
