name: BDD style check
on:
  pull_request:
    paths:
      - "interactive_ai/tests/e2e/**"
      - ".github/workflows/bdd-stylecheck.yml"
  merge_group:
    paths:
      - "interactive_ai/tests/e2e/**"
      - ".github/workflows/bdd-stylecheck.yml"

permissions: {}

jobs:
  style-checks:
    name: Style checks
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
        with:
          version: "0.7.13"

      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: "18.17.0"

      - name: Install swagger-cli and openapi-generator-cli
        run: |
          npm config set registry "http://registry.npmjs.org/"
          npm install -g @apidevtools/swagger-cli
          npm install -g @openapitools/openapi-generator-cli

      - name: Static code analysis
        working-directory: interactive_ai/tests/e2e
        run: |
          openapi-generator-cli version-manager set 7.13.0
          make static-code-analysis
