name: Libraries - tests and stylechecks

on:
  workflow_call:
    inputs:
      component-dir:
        description: "Dir in root directory"
        type: string
        required: true
      ref:
        description: "Ref to checkout"
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: "main"
      component-dir:
        description: "Path to the component (relative to the root of the repository)"
        required: true

permissions: {} # No permissions by default on workflow level

env:
  COMPONENT_DIR: ${{ inputs.component-dir  }}

jobs:
  component-tests:
    name: Component workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          ref: ${{ inputs.ref || '' }}

      - name: Install missing dependencies
        run: |
          sudo -E apt update
          sudo -E apt install -y ffmpeg

      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
        with:
          version: "0.7.13"

      - name: Setup GO
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "1.23"

      - name: Static code analysis
        run: make -C "${COMPONENT_DIR}" static-code-analysis

      - name: Tests
        run: make -C "${COMPONENT_DIR}" tests
