name: Libraries - tests and stylechecks

on:
  workflow_call:
    inputs:
      component-dir:
        description: 'Dir in root directory'
        type: string
        required: true
      ref:
        description: "Ref to checkout"
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: true
        default: 'main'
      component-dir:
        description: 'Path to the component (relative to the root of the repository)'
        required: true

permissions: {} # No permissions by default on workflow level

env:
  COMPONENT_DIR: ${{ inputs.component-dir  }}

jobs:
  component-tests:
    name: Component workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2
        with:
          persist-credentials: false
          ref: ${{ inputs.ref || '' }}

      - name: Install missing dependencies
        run: |
          sudo -E apt update
          sudo -E apt install -y ffmpeg

      - name: Install uv
        uses: astral-sh/setup-uv@a02a550bdd3185dba2ebb6aa98d77047ce54ad21 # v6.2.1
        with:
          version: "0.7.13"

      - name: Setup GO
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: '1.23'

      - name: Static code analysis
        run: make -C "${COMPONENT_DIR}" static-code-analysis

      - name: Tests
        run: make -C "${COMPONENT_DIR}" tests
