permissions: {}

name: Notify Teams on UI PR Creation

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "web_ui/**"

jobs:
  notify-teams:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Notify Teams via Webhook
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        with:
          script: |
            const pr = context.payload.pull_request;
            const card = {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "themeColor": "0076D7",
              "title": `🔔 New UI Pull Request Created!`,
              "text": pr.body ? pr.body.substring(0, 300) : '_No description provided._',
              "sections": [{
                "activityTitle": `**Title:** [${pr.title}](${pr.html_url})`,
                "facts": [
                  { "name": "Author", "value": pr.user.login },
                  { "name": "Branch", "value": `\`${pr.head.ref}\` → \`${pr.base.ref}\`` },
                  { "name": "PR Link", "value": `[View PR](${pr.html_url})` }
                ]
              }]
            };
            await fetch(process.env.TEAMS_WEBHOOK_URL, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(card)
            });
