name: Workflows static analysis

on:
  pull_request:
    branches: ["*"]
    paths:
      - ".github/**"

permissions: {}

jobs:
  zizmor-scan-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run Zizmor scan
        uses: open-edge-platform/anomalib/.github/actions/security/zizmor@5966423da7fe9896500d0595f41c86f3f7bb1f41
        with:
          scan-scope: "changed"
          severity-level: "HIGH"
          confidence-level: "LOW"
          fail-on-findings: true
